-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '68ea335360fed70a' HASH '341e70760ab07a70647aba34d0cbe9caed244580538b7f0eeb77479d7cab1f9b' ADMIN;         
CREATE SEQUENCE "PUBLIC"."TELEFONO_SEQ" START WITH 1 INCREMENT BY 50;         
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_TELEFONO"(
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "USER_ID" UUID,
    "COD_CIUDAD" CHARACTER VARYING(255),
    "COD_PAIS" CHARACTER VARYING(255),
    "NUMERO_FONO" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."HTE_TELEFONO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_TELEFONO;            
CREATE MEMORY TABLE "PUBLIC"."TELEFONO"(
    "ID" BIGINT NOT NULL,
    "USER_ID" UUID,
    "COD_CIUDAD" CHARACTER VARYING(255),
    "COD_PAIS" CHARACTER VARYING(255),
    "NUMERO_FONO" CHARACTER VARYING(255)
);      
ALTER TABLE "PUBLIC"."TELEFONO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TELEFONO;
CREATE MEMORY TABLE "PUBLIC"."USUARIOS"(
    "ESTA_ACTIVO" BOOLEAN NOT NULL,
    "CREADO" TIMESTAMP(6),
    "MODIFICADO" TIMESTAMP(6),
    "ULTIMO_LOGIN" TIMESTAMP(6),
    "ID" UUID NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "NOMBRE" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "TOKEN" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."USUARIOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_39" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIOS;
ALTER TABLE "PUBLIC"."USUARIOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" UNIQUE NULLS DISTINCT ("EMAIL");       
ALTER TABLE "PUBLIC"."TELEFONO" ADD CONSTRAINT "PUBLIC"."FKGKFR99CYQDVS8EN0XC7YJ689P" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USUARIOS"("ID") NOCHECK;    
